# Generated by Django 4.2.1 on 2023-06-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_create', 'title']},
        ),
    ]
