# Generated by Django 4.2.1 on 2023-06-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_post_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
